### ISSUE TITLE
On Windows, media urls in CSS files have back slashes instead of forward slashes.

### ISSUE THREAD

**Issue by bradleyayers** [dziegler/django-css#1]
In compressor/filters/css_default.py line 29:
    full_url = os.path.normpath(full_url)

http://docs.python.org/library/os.path.html#os.path.normpath

"On Windows, it converts forward slashes to backward slashes. It should be understood that this may change the meaning of the path if it contains symbolic links!"

**Comment by bradleyayers** [comment]
After reading http://docs.python.org/library/os.path.html I recommend that instead of using :
    full_url = os.path.normpath(full_url)
You instead use:
    full_url = posixpath.normpath(full_url)

**Comment by dziegler** [comment]
Has this been causing problems for windows users, and does switching os.path to posixpath fix things? I have no idea because I don't use windows, so I'm limited in how much I can really test this.

**Comment by bradleyayers** [comment]
yep, using posixpath makes it perfect.

**Comment by dziegler** [comment]
Ok, I've pushed the change. Thanks catching this.
