### ISSUE TITLE
django-css causes syncdb failure.

### ISSUE THREAD

**Issue by schinckel** [dziegler/django-css#13]
When a project that uses django-css attempts to load, it looks for a site object every time. It is wrapped in a try/except clause, but if the loading is before the django_sites table has been populated, then it creates a transaction error.

This isn't necessarily too bad, but this happens when trying to do an initial syncdb.

Which means the syncdb fails, because a table is missing - that the syncdb needs to create.

The workaround is to disable the `compressor` app until after the syncdb.

**Comment by bryanveloso** [comment]
Ah, this has been happening to me. I never took at a look at the fact that it was looking for Site object, but I have been using this workaround as well.

**Comment by pitaylor** [comment]
Same here. I'm using postgresql -- not sure if other databases are affected. For better or for worse I added this guy to settings.py after INSTALLED_APPS to circumvent the problem:

```
if len(sys.argv) > 1 and sys.argv[1] == 'syncdb':
    INSTALLED_APPS = tuple(app for app in INSTALLED_APPS if app != 'compressor')
```

As for the fix, the `DOMAIN` value could be populated lazily. It would also be nice to have a `COMPRESSOR_CACHE_PREFIX` setting that takes precedence over the site domain name.

**Comment by schinckel** [comment]
I _only_ use postgres, so I can't say for sure: but I would assume it is, since the database query would happen regardless.

**Comment by dziegler** [comment]
I haven't been able to duplicate this, but I'm hoping that oesmith's merge fixes this:
http://github.com/dziegler/django-css/commit/f5bbbed140264e19ce45ce56ad2c893fcb7552a4

can someone confirm?

**Comment by pitaylor** [comment]
Works for me. Thanks!

**Comment by dziegler** [comment]
awesome, closing this out

**Comment by timc3** [comment]
We still get this problem, Python 2.6, Django 1.2.1

**Comment by timc3** [comment]
pitaylor's line works nicely for now though.

**Comment by schinckel** [comment]
Yes, but if the changeset to fix this doesn't work, then it means it is still broken.

**Comment by pitaylor** [comment]
Hmm.. not broken for me. You may want to verify that you see oesmith's change to `compressor/__init__.py` on your machine. Otherwise you may have some code invoking compressor stuff during syncdb that could be causing it.

**Comment by attilaolah** [comment]
@pitaylor adding "compressor" to INSTANNED_APPS will cause an import during syncdb as Django will try to look for models. @dziegler, could you please do a PyPI release for 2.3.0?
