### ISSUE TITLE
django-css and celery test conflict

### ISSUE THREAD

**Issue by gadomski** [dziegler/django-css#14]
I have a project that uses celery (http://ask.github.com/celery/) for some asynchronous background processing. I have some tests that test celery's Task#delay method (http://ask.github.com/celery/reference/celery.task.base.html#celery.task.base.Task.delay). In order to run these tests, per the celery documentation (http://ask.github.com/celery/cookbook/unit-testing.html#testing-with-django), I set CELERY_ALWAYS_EAGER = True in my settings.

The issue comes when I include 'compressor' in my INSTALLED_APPS...when compressor is present, my celery delay tests hang indefinetly. I'm relativly new to python, so I'm not sure of the exact mechanics, but it seems though compressor is invalidating the CELERY_ALWAYS_EAGER setting. I have tried placing 'compressor' above and below 'celery' in my INSTALLED_APPS, to no effect.

I raised the issue here becuase things were working fine before I tried including compressor.

There isn't too much error output to show, but I can send code if that would be helpful to duplicate the problem.

Thanks.

**Comment by dziegler** [comment]
Sorry, this slipped through the cracks...did you ever resolve this issue? We use celery and haven't really had problems, but I always turn compression off when I run tests because we flush the cache before each test.

**Comment by gadomski** [comment]
No sweat. I never resolved the issue. I also am not working on that project anymore so I can't give you too much more information, apologies.

**Comment by gadomski** [comment]
Closing so this gets out of my 'watched issues' queue :-). Since the proj is dead hope that's ok.
