### ISSUE TITLE
Breaks on utf-8 input

### ISSUE THREAD

**Issue by oivvio** [dziegler/django-css#18]
I get a UnicodeDecodeError, when one of the css files to be compressed contains non ascii chars.

As a work around I move the reference to the one unicode css file outside of my compress block.

**Comment by ixc** [comment]
This was fixed in [this commit](http://github.com/ixc/django-css/commit/cb4cb8121e502482197a5596718aef2502cf8da8) in the [ixc fork](http://github.com/ixc/django-css/). Still waiting for the pull request to be approved.

**Comment by dziegler** [comment]
fixed, thanks
