### ISSUE TITLE
CSSTidy Filter Doesn't Work

### ISSUE THREAD

**Issue by bryanveloso** [dziegler/django-css#3]
Christian borrowed the CSSTidy filter from django-compress, but never edited it to work with django_compressor's edited FilterBase class. Since django_compressor proper seems to be dead for the time being, I'm hoping you could make the necessary changes. :)

**Comment by dziegler** [comment]
Your wish is my command :)

Should be fixed now, thanks for letting me know about that.

**Comment by bryanveloso** [comment]
Thank you so much! It really annoyed me to go through all the work to actually get the csstidy executable to work only to not have django_compressor have a way to feed my CSS to it!
