### ISSUE TITLE
charset attribute on link element is not HTML5 compliant

### ISSUE THREAD

**Issue by philippbosch** [dziegler/django-css#5]
The <link> element generated by django-css contains a charset="utf-8" attribute. Unfortunately the charset attribute is not allowed in HTML5 any longer. Maybe there should be a setting for HTML5 mode or similiar.

Thanks for the great app! I was tired of having the LESS compiler running in the background all the time. But no longer.

**Comment by dziegler** [comment]
I just removed the charset attribute altogether, since it's not really necessary. HTML4 should assume utf-8 by default. Thanks for pointing that out.
