### ISSUE TITLE
COMPRESS_URL is not used

### ISSUE THREAD

**Issue by tymofij** [dziegler/django-css#6]
<pre>
compressor/__init__.py , line 66:

    def get_filename(self, url):
        if not url.startswith(settings.MEDIA_URL):
            raise UncompressableFileError('"%s" is not in COMPRESS_URL ("%s") and can not be compressed' % (url, settings.MEDIA_URL))
        basename = url[len(settings.MEDIA_URL):]
        filename = os.path.join(settings.MEDIA_ROOT, basename)
        return filename
</pre>

Despire README telling about the COMPRESS_URL and COMPRESS_ROOT, they are not used in actual file reading.

**Comment by dziegler** [comment]
settings.MEDIA_URL is different from django_settings.MEDIA_URL. settings.MEDIA_URL is imported from compressor.conf. If COMPRESS_URL is defined in your settings.py, then it will equal that. If not, it will default to MEDIA_URL. I added a unit test to check this.

**Comment by GermanoGuerrini** [comment]
Hi,
I got the same problem here.
While it's true that COMPRESS_URL override MEDIA_URL in your settings.py, in your templatetags/compress.py at line 24 you look for a MEDIA_URL key in your context dictionary. In my case, it just happens to have it, and its value is of course django_settings.MEDIA_URL.
        if 'MEDIA_URL' in context:
            media_url = context['MEDIA_URL']
        else:
            media_url = settings.MEDIA_URL
Honestly, I can't see a reason for this check. Can you please confirm this?
Thanks
