### ISSUE TITLE
TemplateSyntaxError with misconfiguration

### ISSUE THREAD

**Issue by ptoal** [dziegler/django-css#7]
Specifying an invalid value for x in  {% compress x %} results in a TemplateSyntaxError:

Caught an exception while rendering: global name 'ALLOWED_ARGS' is not defined

This is due to the fact that ALLOWED_ARGS isn't defined anywhere, and is called in templatetags/compress.py

I've just started working with django-css, and I'm not sure what the allowed args are supposed to be, so I won't suggest a patch. :)

**Comment by dziegler** [comment]
Sorry about that, the allowed args are 'css' or 'js' :)
