### ISSUE TITLE
Limitations of django-css

### ISSUE THREAD

**Issue by robertrv** [dziegler/django-css#8]
I want to know what are limitations of the template tag content, I mean, what can I put inside it ? any other template tag ? Any html element (comments)?

**Comment by robertrv** [comment]
ah, I see that we can't put an already packed javascript, but we can use a minified, is that correct ?

**Comment by dziegler** [comment]
context variables like {{MEDIA_URL}} are ok, I don't know whether or not template tags will work. Anything you put within the {% compress %} block that isn't a <script> or <link> tag will get ignored. As for packed vs minified js, it depends on what compression filter you're using and if it can handle packed or not. I know I've put minified js through YUI and it's worked fine, and I've probably done this with packed as well. In general, I think the different compressors are pretty good at handling these things, I would be surprised if they choked on minified or packed js.
