### ISSUE TITLE
Problem with Unicode in my js files

### ISSUE THREAD

**Issue by robertrv** [dziegler/django-css#9]
When one of my js files has a non ascii char (for example: "camión") I got an UnicodeDecode error

**Comment by varenc** [comment]
some of my inline JS has unicode in it also I get 

UnicodeEncodeError: 'ascii' codec can't encode characters in position 6550-6551: ordinal not in range(128)

I'll go ahead and see I can write a patch to fix this, any ideas would be appreciated though!

**Comment by varenc** [comment]
For my inline js with unicode problem...this fixed it..

in **init**.py change 
        return hashlib.sha1(plaintext).hexdigest()

to
         p = smart_str(plaintext)
        return hashlib.sha1(p).hexdigest()

(and add 'from django.utils.encoding import smart_str') to the top)

**Comment by dziegler** [comment]
Thanks for the patch!
